# Generated by Django 4.2 on 2023-08-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.TextField(default='sadfsa', max_length=13),
            preserve_default=False,
        ),
    ]
