# Generated by Django 4.2 on 2023-08-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
