# Generated by Django 4.2 on 2023-08-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
    ]
