# Generated by Django 4.2 on 2023-08-17 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
